services:
  - type: web
    name: global-hospital
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: global-hospital-db
          property: connectionString

databases:
  - name: global-hospital-db
